version: "3.0"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      # target: prod
    image: adjoined_frontend
    container_name: frontend
    hostname: frontend
    restart: always
    ports:
      - 80:80
    env_file:
      - .env
